### ISSUE TITLE
View Router appears broken

### ISSUE THREAD

**Issue by tutley** [formio/formio-app-todo#2]
I cloned this repository and edited the src/config.js file to point to my API back end. I changed the app url to localhost:3000. I ran npm install, bower install, then gulp serve. The app loads on port 3000 but then it displays an error in the login section showing "Cannot GET /user/login?live=1"

**Comment by travist** [comment]
Hey Tom... I actually have it in my "todo" list to look at this app tonight.  No pun intended... 

I will be updating the app with the latest dependencies so maybe that will help.  Stay tuned...

**Comment by tutley** [comment]
Thank you!

**Comment by travist** [comment]
Hey @tutley.  I was able to get this working just fine by downloading the repo and changing the configs.  I did update the dependencies this morning, so maybe that will help.  Here is what my config looks like. I just changed the APP_URL to your projects api after you created it.

**_/src/config.js**_

```
var APP_URL = 'https://fxmumuwjcdfwmoj.form.io';
var API_URL = 'https://api.form.io';

// Parse query string
var query = {};
location.search.substr(1).split("&").forEach(function(item) {
    query[item.split("=")[0]] = item.split("=")[1] && decodeURIComponent(item.split("=")[1]);
});

angular.module('formioAppTodo').constant('AppConfig', {
  appUrl: query.appUrl || APP_URL,
  apiUrl: query.apiUrl || API_URL
});
```

I then typed the following to run it...

```
npm install
bower install
gulp serve
```

**Comment by tutley** [comment]
Thanks, I'll give this another crack later.

**Comment by tutley** [comment]
Those steps did the trick. I was confused as to the APP url
